### ISSUE TITLE
Authenticate is called for every package install

### ISSUE THREAD

**Issue by anselmstordeur** [bufferoverflow/verdaccio-gitlab#13]
When a package is not scoped we don't need to call authenticate all the time. We DDOSed our private GitLab instance when anyone installed a lot of packages, because GitLab was requested several times even if the package asked for was not scoped and available on public npm.

Request pile up very quickly when installing `express` for example. It makes a request for every package used by `express`.

**Comment by anselmstordeur** [comment]
We tried to implement a cache for the requests to GitLab and failed, because it seems that the file is reloaded every time and we need a persistent cache in a file for example. Caching in a file could be a bad idea, because I don't know how this file is loaded and if it is threadsafe.

**Comment by bufferoverflow** [comment]
Why do you have to limit access? I suggest to only use authentication for publishing. As you figured out there is no caching of credentials in place.

**Comment by anselmstordeur** [comment]
We set up verdaccio for private modules. We want to use the features of npm and not install our (proprietary) modules from GitLab or publish them on npm (registry.npmjs.org)... 

Would be great to use GitLab as authentication provider, because we already use it. Caching the groups would be it. Group owners are not changing very frequently.... Do you have any idea how that could be achieved?

**Comment by torvitas** [comment]
Any chance this is going to be fixed?

**Comment by bufferoverflow** [comment]
PR’s are welcome!

**Comment by kopax** [comment]
I got here because of similar issue. The ldap plugin also get spammed and it is not possible to use user account.

It look  not possible for that plugin,

We wanted to try that one too, GitLab should handle less the spam than OpenLdap but the ldap plugin does not work well at all for the same reason: https://github.com/Alexandre-io/verdaccio-ldap/issues/33

From what I understand, the fix should be done in verdaccio, but right now there is no persistence layer in verdaccio.

**Comment by bufferoverflow** [comment]
https://github.com/idangozlan/verdaccio-bitbucket/blob/master/src/cache.js could be an option to implement this, see also its usage https://github.com/idangozlan/verdaccio-bitbucket/blob/master/src/index.js#L92

**Comment by kopax** [comment]
Interesting, the thing is that it use the application memory to store the object.
This will still result in multiple login if you scale verdaccio up. This could definitively work for the ldap plugin. Why don't you use this in the gitlab plugin? Do you prefere a db service?

**Comment by bufferoverflow** [comment]
I think it makes sense to use https://www.npmjs.com/package/node-cache

**Comment by dlouzan** [comment]
Just FYI, I'm working on an implementation using node-cache as suggested by @bufferoverflow. It's not a perfect solution, but a small, manageable solution. By comments of the maintainer in verdaccio/verdaccio/issues/732, I don't think support for it will be added in the parent project.

**Comment by kopax** [comment]
@dlouzan very good news, let us know when you need people for testing it. I may be able to find time.

**Comment by dlouzan** [comment]
PR in progress; it would be very good if at least two people could review / test this locally. This PR builds on top of another one I made yesterday, and it changes quite a lot of things in the auth handling (I hope for the good).

Definitely some automated testing is needed, but we will see :-)

**Comment by bufferoverflow** [comment]
@kopax I would appreciate if you could test #23 and comment over there.

**Comment by kopax** [comment]
Oh too bad =/, I thought you were doing it on the https://github.com/Alexandre-io/verdaccio-ldap which is the one I wanted to use. Both plugins share the same problem. 

I will test it for you now, and will tell you. Maybe this can be implemented in verdacio-ldap too if it work?

**Comment by dlouzan** [comment]
Ok, I'm sorry for you but I'm not sure how you though this was being done in the ldap plugin, we are on the gitlab plugin repo xD

The cache is completely generic, so adaptations to other plugins are quite easy.

**Comment by kopax** [comment]
@dlouzan I think I was watching other repo to see how they managed to deal with the issue.

I got delayed today but I will definitively test it within next week. Maybe we will replace our ldap auth with this one. 

@juanpicado from verdaccio repo recommended here https://github.com/verdaccio/verdaccio/issues/732#issuecomment-394052082 to implement this in a separate module. This way it could be used on top of any other plugin.

I am not sure how it is supposed to be done as I have not found one yet working like that and haven't worked on any.

**Comment by kopax** [comment]
I am building a docker image in order to perform testing.

One note, I add to use `FROM node:10.1.0-alpine` instead of `FROM node:carbon-alpine` for building the image otherwise I was having: 

```bash
dka@dev-01:[~/workspace/github.com/dlouzan/verdaccio-gitlab (master)]: docker build -t verdaccio .
Sending build context to Docker daemon  620.5kB
Step 1/20 : FROM node:carbon-alpine
 ---> ca148a52ea10
Step 2/20 : LABEL maintainer="https://github.com/bufferoverflow/verdaccio-gitlab"
 ---> Using cache
 ---> b3bdf6d565a4
Step 3/20 : RUN apk --no-cache add openssl &&     wget -O /usr/local/bin/dumb-init https://github.com/Yelp/dumb-init/releases/download/v1.2.0/dumb-init_1.2.0_amd64 &&     chmod +x /usr/local/bin/dumb-init &&     apk del openssl
 ---> Running in 96e65174e580
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/community/x86_64/APKINDEX.tar.gz
(1/3) Installing libcrypto1.0 (1.0.2o-r0)
(2/3) Installing libssl1.0 (1.0.2o-r0)
(3/3) Installing openssl (1.0.2o-r0)
Executing busybox-1.26.2-r11.trigger
OK: 9 MiB in 18 packages
Connecting to github.com (52.74.223.119:443)
ssl_client: github.com: TLS connect failed
wget: error getting response: Connection reset by peer
The command '/bin/sh -c apk --no-cache add openssl &&     wget -O /usr/local/bin/dumb-init https://github.com/Yelp/dumb-init/releases/download/v1.2.0/dumb-init_1.2.0_amd64 &&     chmod +x /usr/local/bin/dumb-init &&     apk del openssl' returned a non-zero code: 1
````

I will let you know very soon of the result, we were experiencing errors in a very bad way and it will be straightforward to verify.

**Comment by bufferoverflow** [comment]
@kopax you need to define `gitlab: true` within packages section, see https://github.com/bufferoverflow/verdaccio-gitlab#use-it then owner of groups are allowed to publish.

**Comment by kopax** [comment]
That was the part I understand @bufferoverflow .

The part I am not understanding is to know 

owner of which group is allowed to publish what?

Again, a concret example would help.

**Comment by bufferoverflow** [comment]
If you are owner of a group within gitlab, then you are allowed to publish a package or a package scope with the same name. So if you are owner of `mycom` and `myorg` on GitLab you can publish scoped packages `@mycom/*` and `@myorg/*` or `mycom` and `myorg` packages.

**Comment by dlouzan** [comment]
Just a side note: you are also owner of packages under your user name as group.

**Comment by dlouzan** [comment]
@kopax I can make another PR, but I don't understand everything (the formatting of your comment is a bit chaotic):
- I agree the verdaccio dockerfile version should be updated, I think it should be the same version as in package.json (as of today 3.1.1). I didn't really work with the docker build, it needs some work.
- I don't understand the issue with `files` in the build, could you please elaborate?
- I'm not sure I get the sentence `We at first could login due to missing personal access token`, but then in the log below a 401 is shown, which is expected, :-?

**Comment by kopax** [comment]
I agree for the formatting.

About Dockerfile, you can update it directly. I am not sure if the image is released to the Docker repo but I believe it should be. (travis CI can be used for that).

So far, I think the Dockerfile must be build by the client and deployed somewhere, @bufferoverflow needs to confirm.

Because of that, I had to manually add the `verdaccio-gitlab` in the container to install it and I have used `npm pack` which prepare the `.tar.gz` as it will be published on npm registry.

If you look at `files`, you will see that you will only include one source, so the script will be broken for every users trying to update.

This was my `Dockerfile` after fixing `files` and doing `npm pack` (I have added to the image my configuration but that is not required)

```Dockerfile
FROM node:10.1.0-alpine
LABEL maintainer="https://github.com/bufferoverflow/verdaccio-gitlab"

RUN apk --no-cache add openssl && \
    wget -O /usr/local/bin/dumb-init https://github.com/Yelp/dumb-init/releases/download/v1.2.0/dumb-init_1.2.0_amd64 && \
    chmod +x /usr/local/bin/dumb-init && \
    apk del openssl

ENV APPDIR /usr/local/app

WORKDIR $APPDIR

ADD . $APPDIR
ADD verdaccio-gitlab-1.0.0.tgz /usr/local/app
ENV NODE_ENV=production

RUN npm config set registry http://registry.npmjs.org/ && \
	npm install -g verdaccio@3.2.0 && \
	npm install -g /usr/local/app/verdaccio-gitlab-1.0.0.tgz
#    npm install -g verdaccio@2.7.3 && \
    #npm install -g verdaccio-gitlab@latest

RUN mkdir -p /verdaccio/storage /verdaccio/conf
ADD conf/config.yaml /verdaccio/conf/config.yaml
ADD conf/htpasswd /verdaccio/htpasswd

#ADD docker-verdaccio-gitlab.config.yaml /verdaccio/conf/config.yaml

RUN addgroup -S verdaccio && adduser -S -G verdaccio verdaccio && \
    chown -R verdaccio:verdaccio "$APPDIR" && \
    chown -R verdaccio:verdaccio /verdaccio

USER verdaccio

ENV PORT 4873
ENV PROTOCOL http

EXPOSE $PORT

VOLUME ["/verdaccio"]

ENTRYPOINT ["/usr/local/bin/dumb-init", "--"]

CMD verdaccio --config /verdaccio/conf/config.yaml --listen $PROTOCOL://0.0.0.0:${PORT}
```


You can ignore the last dot.

**Comment by dlouzan** [comment]
@kopax Ok, so your suggestion regarding the `files` is to remove it completely from `package.json`, and then setup what should be included in the release in the `.npmignore` file, right?

**Comment by kopax** [comment]
Yes, `files` should be banned from `package.json`. It is the worst thing ever.

**Comment by dlouzan** [comment]
Ok, thank for the insights. Later today I'll be publishing some corrections in the currently active PR fixing this. I'll make another one for fixing docker.

**Comment by kopax** [comment]
Any chances to get a release soon?

**Comment by kopax** [comment]
@bufferoverflow regarding configuration : 

```bash
  '@*/*':
    # scoped packages
    access: $authenticated
    publish: $authenticated
    proxy: npmjs
    gitlab: true
```

I am trying to undersdtand how does that work ? Does all the scoped modules get published to the private and public registry ? 

What if a scopped module is private and we do not want to use npmjs?

**Comment by dlouzan** [comment]
That configuration means that in order to access or publish any scoped package, you need to be authenticated in verdaccio. On top, the gitlab plugin will only allow you to publish the package if either:
- Your user name is exactly the same as the scope of the package, or
- You are owner in gitlab of a group that matches the name of the scope (equivalently, as long as you  are owner of a group, you can publish any package below it)

It might be worth to implement further access control at the read (`allow_access` method) level in the future, but right now in order to read the package you just need to be authenticated.

Packages are only published in the private verdaccio registry, no upstream publish is done.
