### ISSUE TITLE
is dumb-init really required?

### ISSUE THREAD

**Issue by bufferoverflow** [bufferoverflow/verdaccio-gitlab#32]
Today as used within verdaccio docker image, dumb-init is used, see https://github.com/bufferoverflow/verdaccio-gitlab/blob/master/Dockerfile#L39 .

Do we really need that ? How is kubernetes and Openshift handling this?

- https://github.com/nodejs/docker-node/blob/master/docs/BestPractices.md#handling-kernel-signals
- https://github.com/krallin/tini#using-tini

The node image is using the node user, see https://github.com/nodejs/docker-node/blob/master/docs/BestPractices.md#non-root-user, so using this instead of the verdaccio user would simplify that.

/cc @dlouzan @ercanucan

**Comment by juanpicado** [comment]
cc: @sergiohgz

**Comment by juanpicado** [comment]
I wonder whether @markpeterfejes has an opinion on it.  
https://github.com/verdaccio/verdaccio/commit/32709843fb17614e19e84500026ad6e4a45bff69

**Comment by dlouzan** [comment]
We are trying to run the docker image in openshift and having some issues with permissions. We are almost sure it is because of the default policy of openshift of randomizing user guids on startup. Trying some official docker hub images in openshift shows similar results, some work and some don't, depending on how the docker build is made.

We'll be posting some information about the findings, in case we can make both verdaccio and verdaccio-gitlab (since they both build the docker image the same way) generically compatible with that.

**Comment by bufferoverflow** [comment]
Thanks all for the investigations on this!
