### ISSUE TITLE
Questions before contributing

### ISSUE THREAD

**Issue by blackholegalaxy** [bufferoverflow/verdaccio-gitlab#65]
I'd like to add some features on this package, but I have some questions before contributing.

 1. Could you explain why we initialize a global tunnel in `src/verdaccio.js`?

2. I see despite the fact we use verdaccio `3.x` in `package.json` dependencies, we build docker image using `4.x-next` base verdaccio docker image. Could this cause instability because we build a plugin for an older version of verdaccio than the one used in the base docker image?

**Comment by dlouzan** [comment]
Hello, thanks for participating in the project!

1. The global tunnel is used for compatibility with corporate environments, where internal proxies are used. With no explicit configuration, it will use the `http(s)_proxy` variables from the environment (see the [official docs](https://www.npmjs.com/package/global-tunnel-ng#auto-config)).
1. The docker image is built based on 4.x because there's heavy refactoring of the docker image in verdaccio 4.x and we built on top of it. @juanpicado has promised to keep 4.x quite stable and shouldn't be long for a release (or so I hope :-)

**Comment by dlouzan** [comment]
Sorry I didn't fully answer your plugins question: yes, that might be the case. Although as of today we hadn't found any issues, it could happen. I'll open an issue to track this.

**Comment by juanpicado** [comment]
> has promised to keep 4.x quite stable and shouldn't be long for a release (or so I hope :-)

My soul was just sold 😆 . Yes, hopefully we finish the UI along February and couple of things and we can launch a beta with no further additions for a month. Then, big release.

**Comment by blackholegalaxy** [comment]
Thanks for explainations!

**Comment by bufferoverflow** [comment]
closing this as we are on 4 now
